version: 0.2

env:
  variables:
    aws_s3_bucket_Target_Name_0: "your-bucket-name"  # Nome do bucket S3 onde estão os arquivos
    Command: "apply,/path/to/states"  # Comando e caminho, definir conforme necessário

phases:
  install:
    commands:
      - echo "Reading and initializing the Command variable..."
      - |
        command_array=(${Command//,/ })
        command_type=${command_array[0]}
        path=${command_array[1]}
        echo "Command Type: $command_type"
        echo "Path: $path"
      - echo "Installing Python dependencies..."
      - pip install boto3  # Instala boto3
      - echo "Downloading List.txt file from S3..."
      - aws s3 cp s3://${aws_s3_bucket_Target_Name_0}/${path}/List.txt ./List.txt
      - echo "Content of the List.txt file:"
      - cat ./List.txt
      - echo "Installing Terraform..."
      - wget -q https://releases.hashicorp.com/terraform/1.5.5/terraform_1.5.5_linux_amd64.zip
      - unzip terraform_1.5.5_linux_amd64.zip
      - mkdir -p ~/.local/bin
      - mv terraform ~/.local/bin/
      - export PATH=$PATH:~/.local/bin
      - terraform --version  # Verifica se o Terraform foi instalado corretamente

  pre_build:
    commands:
      - echo "Preparing build..."
      - echo "Syncing Terraform plugins from S3 to avoid re-downloading during init..."
      - mkdir -p /tmp/terraform/plugins/
      - aws s3 sync s3://${aws_s3_bucket_Target_Name_0}/terraform-plugin-dir/.terraform/ /tmp/terraform/plugins/ --quiet
      - echo "Accessing the file from S3 bucket..."

  build:
    commands:
      - echo "Executing TerraBatch script..."
      - python TerraBatch.py

  post_build:
    commands:
      - echo "Syncing updated Terraform plugins back to S3..."
      - aws s3 sync /tmp/terraform/plugins/ s3://${aws_s3_bucket_Target_Name_0}/terraform-plugin-dir/.terraform/ --quiet
      - echo "Build completed successfully!"
