version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Instalando dependências do Terraform..."
      - curl -O https://releases.hashicorp.com/terraform/1.4.0/terraform_1.4.0_linux_arm64.zip --silent
      - unzip -q terraform_1.4.0_linux_arm64.zip
      - mkdir -p ~/.local/bin
      - mv terraform ~/.local/bin/
      - export PATH=$PATH:~/.local/bin
      - echo "Instalando dependências do Python..."
      - pip install boto3 requests --quiet

  pre_build:
    commands:
      - echo "Preparando o ambiente de trabalho..."
      - mkdir -p /tmp/states/${STATE_NAME}/
      - echo "Baixando arquivos Terraform e lockfile do S3..."
      - aws s3 cp s3://${AWS_S3_BUCKET_SOURCE_NAME_0}/states/${STATE_NAME}/ /tmp/states/${STATE_NAME}/ --recursive --quiet
      - echo "Renomeando terraform.lock.hcl para .terraform.lock.hcl, se necessário..."
      - if [ -f /tmp/states/${STATE_NAME}/terraform.lock.hcl ]; then
          mv /tmp/states/${STATE_NAME}/terraform.lock.hcl /tmp/states/${STATE_NAME}/.terraform.lock.hcl;
        fi
      - echo "Arquivos baixados do S3:"
      - ls -al /tmp/states/${STATE_NAME}
      - echo "Modificando o arquivo main.tf e baixando arquivos adicionais do S3..."
      - python modify_main_tf.py

  build:
    commands:
      - echo "Executando o script InitTerraform.py..."
      - python InitTerraform.py
      - echo "Verificando se o terraform.lock.hcl foi criado..."
      - ls -al /tmp/states/${STATE_NAME}/

artifacts:
  files:
    - '**/*'
