version: 0.2

env:
  variables:
    USER_ID: "seu_usuario_id"
    STATE_NAME: "seu_state_name"
    COMMAND: "apply"  # ou "plan", "destroy", etc.
    AWS_S3_BUCKET_SOURCE_NAME_0: "your-bucket-name"
  export:
    TF_PLUGIN_CACHE_DIR: "/tmp/.terraform.d/plugin-cache"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Instalando dependências do Terraform..."
      - curl -O https://releases.hashicorp.com/terraform/1.4.0/terraform_1.4.0_linux_arm64.zip --silent
      - unzip -q terraform_1.4.0_linux_arm64.zip
      - mkdir -p ~/.local/bin
      - mv terraform ~/.local/bin/
      - export PATH=$PATH:~/.local/bin
      - echo "Instalando dependências do Python..."
      - pip install boto3 requests --quiet

  pre_build:
    commands:
      - echo "Preparando o ambiente..."
      - mkdir -p /tmp/states/${STATE_NAME}/
      - echo "Sincronizando cache de plugins do Terraform do S3..."
      - aws s3 sync s3://${AWS_S3_BUCKET_SOURCE_NAME_0}/terraform-plugin-cache/ $TF_PLUGIN_CACHE_DIR/ --quiet
      - echo "Baixando arquivos Terraform e lockfile do S3..."
      - aws s3 cp s3://${AWS_S3_BUCKET_SOURCE_NAME_0}/states/${STATE_NAME}/ /tmp/states/${STATE_NAME}/ --recursive --quiet
      - echo "Renomeando terraform.lock.hcl para .terraform.lock.hcl, se necessário..."
      - if [ -f /tmp/states/${STATE_NAME}/terraform.lock.hcl ]; then
          mv /tmp/states/${STATE_NAME}/terraform.lock.hcl /tmp/states/${STATE_NAME}/.terraform.lock.hcl;
        fi
      - echo "Arquivos baixados do S3:"
      - ls -al /tmp/states/${STATE_NAME}
      - echo "Modificando o arquivo main.tf e baixando arquivos adicionais do S3..."
      - python modify_main_tf.py

  build:
    commands:
      - echo "Executando o build..."
      - python InitTerraform.py
      - echo "Verificando se o terraform.lock.hcl foi criado..."
      - ls -al /tmp/states/${STATE_NAME}/

  post_build:
    commands:
      - echo "Sincronizando cache de plugins do Terraform para o S3..."
      - aws s3 sync $TF_PLUGIN_CACHE_DIR/ s3://${AWS_S3_BUCKET_SOURCE_NAME_0}/terraform-plugin-cache/ --quiet
      - if [ -f /tmp/states/${STATE_NAME}/terraform.lock.hcl ]; then
          aws s3 cp /tmp/states/${STATE_NAME}/terraform.lock.hcl s3://${AWS_S3_BUCKET_SOURCE_NAME_0}/states/${STATE_NAME}/terraform.lock.hcl --quiet;
        elif [ -f /tmp/states/${STATE_NAME}/.terraform.lock.hcl ]; then
          aws s3 cp /tmp/states/${STATE_NAME}/.terraform.lock.hcl s3://${AWS_S3_BUCKET_SOURCE_NAME_0}/states/${STATE_NAME}/terraform.lock.hcl --quiet;
        else
          echo "Lockfile não encontrado, não há necessidade de sincronizar.";
        fi
      - echo "Build completado."

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - '/tmp/.terraform.d/plugin-cache/**/*'
