name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main  # Ou a sua branch principal
    paths:
      - 'Docker/TaskHub/**' # Dispara apenas se houver mudanças nesta pasta

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Docker/TaskHub/ # Pasta onde está o Dockerfile e o EC2Hub.py
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ec2hub:latest
            ghcr.io/${{ github.repository_owner }}/ec2hub:${{ github.sha }}
          # O context garante que o Docker encontre o requirements.txt e o EC2Hub.py
