version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-west-1"

phases:
  install:
    runtime-versions:
      python: 3.x
  build:
    commands:
      - echo "Reading input artifact..."
      - aws s3 cp s3://$CODEPIPELINE_ARTIFACT_BUCKET/$CODEPIPELINE_ARTIFACT_OBJECT source-file.txt
      - echo "Transforming content to uppercase..."
      - awk '{ print toupper($0) }' source-file.txt > output-file.txt
      - echo "Uploading output artifact..."
      - aws s3 cp output-file.txt s3://$CODEPIPELINE_ARTIFACT_BUCKET/$CODEPIPELINE_ARTIFACT_OBJECT_OUTPUT

artifacts:
  files:
    - $CODEPIPELINE_ARTIFACT_OBJECT_OUTPUT
