#!/bin/bash

LOGFILE="/var/log/user-data.log"
exec >$LOGFILE 2>&1

#Read environment variables generated by Cloudman
ENV_VARS=""
while IFS= read -r line; do
    KEY=$(echo "$line" | cut -d'=' -f1)
    VALUE=$(echo "$line" | cut -d'=' -f2)
    ENV_VARS+="<p>${KEY}: ${VALUE}</p>"
done </etc/environment

echo "Atualizando o sistema..."
yum update -y

echo "Instalando EPEL..."
sudo amazon-linux-extras install epel -y

echo "Instalando Nginx e Git..."
yum install -y nginx git

echo "Iniciando e habilitando o Nginx..."
systemctl start nginx
systemctl enable nginx

# Download an install CloudWatch agent
wget https://s3.amazonaws.com/amazoncloudwatch-agent/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm
sudo rpm -U amazon-cloudwatch-agent.rpm
sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/opt/aws/amazon-cloudwatch-agent/etc/config.json -s

#Get IMDSv2 Token
METADATA_TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")

#Get IMDSv2 instance Matadata
INSTANCE_ID=$(curl -s -H "X-aws-ec2-metadata-token: $METADATA_TOKEN" http://169.254.169.254/latest/meta-data/instance-id)
PUBLIC_IP=$(curl -s -H "X-aws-ec2-metadata-token: $METADATA_TOKEN" http://169.254.169.254/latest/meta-data/public-ipv4)
AZ=$(curl -s -H "X-aws-ec2-metadata-token: $METADATA_TOKEN" http://169.254.169.254/latest/meta-data/placement/availability-zone)
INSTANCE_TYPE=$(curl -s -H "X-aws-ec2-metadata-token: $METADATA_TOKEN" http://169.254.169.254/latest/meta-data/instance-type)

# Game 2048 repository clone
cd /usr/share/nginx/html
git clone https://github.com/gabrielecirulli/2048.git

# Welcome HTML page
echo "<!DOCTYPE html>
<html>
<head>
    <title>Welcome to 2048</title>
</head>
<body>
    <h2>Welcome to 2048 on AWS</h2>
    <p>Instance ID: ${INSTANCE_ID}</p>
    <p>Public IP: ${PUBLIC_IP}</p>
    <p>Availability Zone: ${AZ}</p>
    <p>Instance Type: ${INSTANCE_TYPE}</p>
    <h2>Environment Variables</h2>
    ${ENV_VARS}
    <button onclick=\"window.location.href='/2048'\">Start Game</button>
</body>
</html>" >/usr/share/nginx/html/index.html

systemctl restart nginx
